apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: efxtbg6d2-nodejs 
  janus-idp.io/tekton: efxtbg6d2-nodejs
  backstage.io/kubernetes-id: efxtbg6d2-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: efxtbg6d2-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml